# Generated by Django 5.0.6 on 2024-05-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mudahJeApps', '0002_remove_question_quiz_remove_result_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerID', models.CharField(max_length=10, unique=True)),
                ('answerText', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questID', models.CharField(max_length=10, unique=True)),
                ('questText', models.CharField(max_length=200)),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudahJeApps.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCorrect', models.BooleanField(default=False)),
                ('totalQuest', models.IntegerField()),
                ('pct', models.IntegerField()),
                ('questID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudahJeApps.question')),
            ],
        ),
    ]
